version: '3.8'
services:
  postfix-exporter:
    build:
      context: .
    ports:
      - "9115:9115"
    volumes:
      - /var/log:/var/log:ro
      - /var/spool/postfix:/var/spool/postfix:ro
    command: ["--config", "/app/config.yaml", "--log-unsupported", "--logfile", "/var/log/mail.log", "--postqueue"]
