version: '3.8'
services:
  postfix-exporter:
    build:
      context: .
    ports:
      - "9115:9115"
    volumes:
      - /var/log:/var/log
      - /usr/sbin/postqueue:/usr/sbin/postqueue:ro
      - /var/spool/postfix/public/showq:/var/spool/postfix/public/showq
    command: ["--config", "/app/config.yaml", "--log_unsupported_lines", "--logfile", "/var/log/mail.log", "--postqueue"]